tap "homebrew/bundle"
tap "homebrew/services"
tap "nextfire/tap"
brew "age"
brew "webp"
brew "jpeg-xl"
brew "chezmoi"
brew "coreutils"
brew "dockutil"
brew "harfbuzz"
brew "leptonica"
brew "tesseract"
brew "ffmpeg"
brew "gh"
brew "git"
brew "go"
brew "gobject-introspection"
brew "imagemagick"
brew "mas"
brew "neovim"
brew "nmap"
brew "rclone"
brew "shpotify"
brew "wget"
brew "nextfire/tap/apple-music-discord-rpc"
cask "1password"
cask "ableton-live-suite@10"
cask "adobe-creative-cloud"
cask "discord"
cask "docker"
cask "dropbox"
cask "figma"
cask "google-chrome@beta"
cask "google-cloud-sdk"
cask "handbrake"
cask "iterm2"
cask "native-access"
cask "notion"
cask "obs"
cask "openmtp"
cask "slack"
cask "sonos"
cask "splice"
cask "spotify"
cask "steam"
cask "telegram"
cask "transcribe"
cask "visual-studio-code"
cask "vlc@nightly"
cask "wireshark"
mas "1Password for Safari", id: 1569813296
mas "ColorSlurp", id: 1287239339
mas "Culture Concorde", id: 1088330492
mas "Darkroom", id: 953286746
mas "File Viewer", id: 495987613
mas "Flow", id: 1423210932
mas "GIPHY CAPTURE", id: 668208984
mas "Logic Pro", id: 634148309
mas "NepTunes", id: 1006739057
mas "Onigiri", id: 1639917298
mas "Skitch", id: 425955336
mas "The Unarchiver", id: 425424353
mas "TickTick", id: 966085870
mas "Tomito", id: 1526042938
vscode "golang.go"
vscode "grapecity.gc-excelviewer"
vscode "gruntfuggly.todo-tree"
vscode "icrawl.discord-vscode"
vscode "idleberg.hopscotch"
vscode "mechatroner.rainbow-csv"
vscode "ms-python.debugpy"
vscode "ms-python.isort"
vscode "ms-python.python"
vscode "ms-python.vscode-pylance"
vscode "ms-toolsai.jupyter"
vscode "ms-toolsai.jupyter-keymap"
vscode "ms-toolsai.jupyter-renderers"
vscode "ms-toolsai.vscode-jupyter-cell-tags"
vscode "ms-toolsai.vscode-jupyter-slideshow"
vscode "ms-vscode-remote.remote-ssh"
vscode "ms-vscode-remote.remote-ssh-edit"
vscode "ms-vscode.cmake-tools"
vscode "ms-vscode.cpptools"
vscode "ms-vscode.cpptools-extension-pack"
vscode "ms-vscode.cpptools-themes"
vscode "ms-vscode.powershell"
vscode "ms-vscode.remote-explorer"
vscode "redhat.vscode-yaml"
vscode "sdras.night-owl"
vscode "tamasfe.even-better-toml"
vscode "twxs.cmake"
vscode "yzhang.markdown-all-in-one"
